version: '3.8'

services:
  telur-pedia:
    build: .
    container_name: telur-pedia
    ports:
      - "8000:80"
    volumes:
      - ./data.json:/var/www/html/data.json
    restart: unless-stopped
